title: Functional Connectivity Development along the Sensorimotor-Association Axis Enhances the Cortical Hierarchy
description: <br>Project Information and Reproducibility Guide
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
